import Head from 'next/head'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <div>1</div>
        <div>2</div>
        <div>3</div>
      </main>

      <footer className=''>
        
      </footer>
    </div>
  )
}
